import React from 'react';

import AlertIconSrc from './alert.svg';
import AngleDownIconSrc from './angle-down.svg';
import AngleUpIconSrc from './angle-up.svg';
import ArrowDownIconSrc from './arrow-down.svg';
import ArrowRightIconSrc from './arrow-right.svg';
import ArrowUpIconSrc from './arrow-up.svg';
import AudioIconSrc from './audio.svg';
import BellIconSrc from './bell.svg';
import BoltIconSrc from './bolt.svg';
import BoxCubeIconSrc from './box-cube.svg';
import BoxIconLineSrc from './box-line.svg';
import BoxIconSrc from './box.svg';
import CalenderIconSrc from './calender-line.svg';
import ChatIconSrc from './chat.svg';
import CheckCircleIconSrc from './check-circle.svg';
import CheckLineIconSrc from './check-line.svg';
import ChevronDownIconSrc from './chevron-down.svg';
import ChevronLeftIconSrc from './chevron-left.svg';
import ChevronUpIconSrc from './chevron-up.svg';
import CloseLineIconSrc from './close-line.svg';
import CloseIconSrc from './close.svg';
import CopyIconSrc from './copy.svg';
import DocsIconSrc from './docs.svg';
import DollarLineIconSrc from './dollar-line.svg';
import DownloadIconSrc from './download.svg';
import EnvelopeIconSrc from './envelope.svg';
import EyeCloseIconSrc from './eye-close.svg';
import EyeIconSrc from './eye.svg';
import FileIconSrc from './file.svg';
import FolderIconSrc from './folder.svg';
import GridIconSrc from './grid.svg';
import GroupIconSrc from './group.svg';
import HorizontaLDotsSrc from './horizontal-dots.svg';
import ErrorIconSrc from './info-hexa.svg';
import InfoIconSrc from './info.svg';
import ListIconSrc from './list.svg';
import LockIconSrc from './lock.svg';
import MailIconSrc from './mail-line.svg';
import MoreDotIconSrc from './more-dot.svg';
import PageIconSrc from './page.svg';
import PaperPlaneIconSrc from './paper-plane.svg';
import PencilIconSrc from './pencil.svg';
import PieChartIconSrc from './pie-chart.svg';
import PlugInIconSrc from './plug-in.svg';
import PlusIconSrc from './plus.svg';
import ShootingStarIconSrc from './shooting-star.svg';
import TableIconSrc from './table.svg';
import TaskIconSrc from './task-icon.svg';
import TimeIconSrc from './time.svg';
import TrashBinIconSrc from './trash.svg';
import UserCircleIconSrc from './user-circle.svg';
import UserIconSrc from './user-line.svg';
import VideoIconSrc from './videos.svg';

function toComponent(mod: any) {
  const value = mod && (mod.default ?? mod);
  if (typeof value === 'string') {
    return (props: React.ImgHTMLAttributes<HTMLImageElement>) =>
      React.createElement('img', { src: value, alt: '', ...props });
  }
  if (typeof value === 'function') {
    return (props: any) => React.createElement(value, props);
  }
  return () => null;
}

export const DownloadIcon = toComponent(DownloadIconSrc);
export const BellIcon = toComponent(BellIconSrc);
export const MoreDotIcon = toComponent(MoreDotIconSrc);
export const FileIcon = toComponent(FileIconSrc);
export const GridIcon = toComponent(GridIconSrc);
export const AudioIcon = toComponent(AudioIconSrc);
export const VideoIcon = toComponent(VideoIconSrc);
export const BoltIcon = toComponent(BoltIconSrc);
export const PlusIcon = toComponent(PlusIconSrc);
export const BoxIcon = toComponent(BoxIconSrc);
export const CloseIcon = toComponent(CloseIconSrc);
export const CheckCircleIcon = toComponent(CheckCircleIconSrc);
export const AlertIcon = toComponent(AlertIconSrc);
export const InfoIcon = toComponent(InfoIconSrc);
export const ErrorIcon = toComponent(ErrorIconSrc);
export const ArrowUpIcon = toComponent(ArrowUpIconSrc);
export const FolderIcon = toComponent(FolderIconSrc);
export const ArrowDownIcon = toComponent(ArrowDownIconSrc);
export const ArrowRightIcon = toComponent(ArrowRightIconSrc);
export const GroupIcon = toComponent(GroupIconSrc);
export const BoxIconLine = toComponent(BoxIconLineSrc);
export const ShootingStarIcon = toComponent(ShootingStarIconSrc);
export const DollarLineIcon = toComponent(DollarLineIconSrc);
export const TrashBinIcon = toComponent(TrashBinIconSrc);
export const AngleUpIcon = toComponent(AngleUpIconSrc);
export const AngleDownIcon = toComponent(AngleDownIconSrc);
export const PencilIcon = toComponent(PencilIconSrc);
export const CheckLineIcon = toComponent(CheckLineIconSrc);
export const CloseLineIcon = toComponent(CloseLineIconSrc);
export const ChevronDownIcon = toComponent(ChevronDownIconSrc);
export const ChevronUpIcon = toComponent(ChevronUpIconSrc);
export const PaperPlaneIcon = toComponent(PaperPlaneIconSrc);
export const EnvelopeIcon = toComponent(EnvelopeIconSrc);
export const LockIcon = toComponent(LockIconSrc);
export const UserIcon = toComponent(UserIconSrc);
export const CalenderIcon = toComponent(CalenderIconSrc);
export const EyeIcon = toComponent(EyeIconSrc);
export const EyeCloseIcon = toComponent(EyeCloseIconSrc);
export const TimeIcon = toComponent(TimeIconSrc);
export const CopyIcon = toComponent(CopyIconSrc);
export const ChevronLeftIcon = toComponent(ChevronLeftIconSrc);
export const UserCircleIcon = toComponent(UserCircleIconSrc);
export const ListIcon = toComponent(ListIconSrc);
export const TableIcon = toComponent(TableIconSrc);
export const PageIcon = toComponent(PageIconSrc);
export const TaskIcon = toComponent(TaskIconSrc);
export const PieChartIcon = toComponent(PieChartIconSrc);
export const BoxCubeIcon = toComponent(BoxCubeIconSrc);
export const PlugInIcon = toComponent(PlugInIconSrc);
export const DocsIcon = toComponent(DocsIconSrc);
export const MailIcon = toComponent(MailIconSrc);
export const HorizontaLDots = toComponent(HorizontaLDotsSrc);
export const ChatIcon = toComponent(ChatIconSrc);
